### ISSUE TITLE
Lab 2 List Exercise 1 Tweaks

### ISSUE THREAD

**Issue by JonKragskow** [pythoninchemistry/ch12004#1]
Students seem to struggle with the first `list`s exercise of Lab 2:

> 1. Copy the following block of code into a Jupyter notebook:
> ```
> colours = [['Red', 'Magenta'], 
>            ['Cyan', 'Green'], 
>            [['Yellow', 'Blue'], 'White']]
> 
> # Insert your own code here.
> 
> print(f'{colour_1} + {colour_2} -> {colour_3}')
> ```
> Using list indexing, assign 'Red' to colour_1, 'Green' to colour_2 and 'Yellow' to colour_3 so that the print statement runs without error and displays a true statement.

I personally think this is quite clear, but a lot of students didn't quite grasp that the key skill here is to index `colours` and assign the resulting values to a set of variables. Perhaps we could add something before the colour mixing print statement which gets them to think about indexing?

> 1. Copy the following block of code into a Jupyter notebook:
> ```
> colours = [['Red', 'Magenta'], 
>            ['Cyan', 'Green'], 
>            [['Yellow', 'Blue'], 'White']]
> ```
> 1a. Using indexing, print the 'Magenta' entry from this list
> 
> 1b. Again using list indexing, assign 'Red' to colour_1, 'Green' to colour_2 and 'Yellow' to colour_3 so that the following print statement runs without error and displays a true statement.
> ```
> print(f'{colour_1} + {colour_2} -> {colour_3}')
> ```

Happy to make a PR if there is any agreement!

**Comment by bjmorgan** [comment]
This sounds like a good suggestion. I might change the wording for 1b so that it is clearer that they shouldn't just do
```python
colour_1 = 'Red'
colour_2 = 'Green'
colour_3 = 'Yellow'
print(f'{colour_1} + {colour_2} -> {colour_3}')
```
(also, they need to figure out which combination of primary colours gives them a secondary colour in the nested list).

**Comment by PatrickJTaylor** [comment]
Thanks again for this @JonKragskow - I had a spare moment this morning and opened a quick PR based on your suggestions. 

The question now reads:

**1**: Copy the following block of code into a Jupyter notebook:

```python
colours = [['Red', 'Magenta'], 
           ['Cyan', 'Green'],
           [['Yellow', 'Blue'], 'White']]
```

a) By using **list indexing**, print just the `Magenta` string from the `colours` list.

b) Again using **list indexing** as above, assign the `Red` element to a variable called `colour_1`, `Green` to a variable called `colour_2` and `Yellow` to a variable called `colour_3` so that the following line of code runs without error and displays a true statement:

```python
print(f'{colour_1} + {colour_2} -> {colour_3}')
```

I can't think of much else we could do to make it clearer but am open to suggestions if you have any, otherwise I'll merge the changes and we'll see what happens when students get to this next year 😅
